# Generated by Django 4.2.1 on 2023-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='gallery-3.jpg', upload_to='profile_images'),
        ),
    ]
